version: 0.2

env:
  variables:
    DYNAMODB_FHE_ALEXA_PRD_DB_TABLE_NAME: "fhe-alexa-prd-db-dynamodb"

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
      - python lambda_function.py test --verbose True
artifacts:
  files:
    - '**/*'
  discard-paths: no