version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
      - python lambda_function.py test --verbose True
artifacts:
  files:
    - '**/*'
  discard-paths: no